export const routes = {
  home: "/",
  product: (productId: string = ":productId") => `/produto/${productId}`,
  category: (category: string = ":category") => `/categoria/${category}`,
  login: "/login",
  profile: "/perfil",
  adminDashboard: "/admin",
  cart: "/carrinho",
  checkout: "/checkout",
  checkoutStep: (step: string = ":step") => `/checkout/${step}`,
  help: "/ajuda",
  about: "/sobre",
  productCreate: "/admin/produtos/novo",
  institutional: (slug: string = ":slug") => `/institucional/${slug}`,
  search: (query?: string) => `/busca${query ? `?q=${encodeURIComponent(query)}` : ""}`,
} as const;
